PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT (COUNT(?statementSubject) as ?count)
WHERE
{
    # For example all triples where the subject is an instance of a class defined by SKOS core
    VALUES ?ontology { <http://www.w3.org/2004/02/skos/core> }

    ?class
        rdfs:isDefinedBy ?ontology ;
        a owl:Class .

    ?statementSubject
        a ?class ;
        ?p ?o .
}
